---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dev.xingzheai.cn.dev.xingzheai.cn
  resources:
  - gssscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.xingzheai.cn.dev.xingzheai.cn
  resources:
  - gssscalers/finalizers
  verbs:
  - update
- apiGroups:
  - dev.xingzheai.cn.dev.xingzheai.cn
  resources:
  - gssscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - game.kruise.io
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.kruise.io
  resources:
  - gameservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets/status
  verbs:
  - get
  - patch
  - update
